CC = gcc
OPT = -g -O3 -ffast-math -funroll-loops
CFLAGS = -Wall 
LDFLAGS = 
OBJECTS = matrixmatrix.o
excer1: $(OBJECTS)
	$(CC) $(CFLAGS) $(OPT) $(LDFLAGS) -o matmul_blk $(OBJECTS)

clean:
	@rm -f *.o core